### PR TITLE
update to latest lean

### PR DESCRIPTION
**Pull request by digama0**
@larsk21 , what are your thoughts on handing over maintenance of this project? I see you have not worked on this since the masters and I'm guessing you don't intend to work on it anymore.

### CODE REVIEW

**Comment by larsk21** [comment]
Since for my PhD I'm working on a topic not involving Lean, I (at least for now) unfortunately don't have the time to work on this project. So, I'm more than happy if someone wants to continue working on it. If you have plans to maintain the project, how do you suggest we do this? Should I add you as a collaborator or transfer the project to, e.g., [leanprover-community](https://github.com/leanprover-community)?

**Comment by digama0** [comment]
I discussed this with the other maintainers and we're on board with transferring the repo to leanprover-community. I think you won't be able to do it directly; the options I have found so far are for you to transfer the repo to my personal account and then I transfer it to leanprover-community; or you add me as an admin on this repo, whereupon I can trigger the transfer.

**Comment by larsk21** [comment]
Great to hear! :) I can surely add you as an admin for this repo, such that you can then transfer it.

Before doing so, I figured it would be good to add a license to the repo. As most Lean-related repos seem to use the Apache-2.0 license and I don't have an interest in restricted the usage of the repo further, I would go with this one, if you don't have any objections.

**Comment by digama0** [comment]
Sounds good to me.

**Comment by digama0** [comment]
Oh, if we are making this repo look more like mathlib then we should probably put copyright headers on all the files, with you as author and the year you wrote this stuff.

**Comment by larsk21** [comment]
Alright, I can do that.

**Comment by Kha** [comment]
> Oh, if we are making this repo look more like mathlib then we should probably put copyright headers on all the files, with you as author and the year you wrote this stuff.

I don't mind either way, just curious (because I may have forgotten): is this a style the community simply copied from Lean, which copied it from MS style? Or is it something the community actively prefers? I find that for open-source projects, the GitHub generated contributors list is mostly sufficient and in particular more up to date (whole-repo copies from ports notwithstanding!)

**Comment by digama0** [comment]
As far as I know it was just copied. But the authors list is not easily replaced: it includes "significant authors" not just anyone who touched the file, and as you point out the port has probably permanently messed up the github author list for mathlib4.

**Review by larsk21 — APPROVED** [review]

**Comment by digama0** [comment]
Okay, I've deleted my repository (this PR was a casualty, but I can re-add it once the repo makes it to its new home). Hopefully you should be clear to transfer the repo to me now.

**Pull request closed without merging**
